- comskip.c
This makes it easier to debug pts based output formats by showing the pts at various events during the comskip lifecycle.
> Show pts for framenums in debug logs

- comskip.c
```
Average framerate:          29.784
Total commercial length:    0:00:23.82
Cut codes:
F: scene	 c: change
A: aspect	 t: cutscene
E: exceeds	 l: logo
L: logo	 v: volume
B: bright	 s: scene_change
C: combined	 a: aspect_ratio
N: nonstrict	 u: uniform_frame
S: strict	 b: black_frame
r: resolution
----------------------------------------------------
Block list after weighing
----------------------------------------------------
```
> Show legend/cheatsheet of cut codes for debugging

- comskip.c
Adds a `ts` and `te` column to the block list table.
before:
```
Block list after weighing
----------------------------------------------------
0:--   13   0  13      1    725   4.00   24.157  0.14   0 1.34          A L    v a b   837+ 0.00 2194+ 94+  0.000    83
1:++   17  14   3    726   2132   0.01   46.914  0.01   0 1.78            L        b   110- 0.61 2609+ 96+  0.000    11
2:++    6   4   2   2133  17328   0.00  507.073  0.03   0 1.78           EL       ub   283- 0.93 1825+ 88+  0.000    28
3:--    5   3   2  17329  17483   5.08    5.138  0.39   4 1.78            LCN     ub  3677+ 0.00 1776- 91+  0.000   367
```
after:
```
Block list after weighing
----------------------------------------------------
0:--    4   0   4      1    715     0.77s    24.59s    23.82s   2.00  0.12   0 …
```
> Show pts start and end markers in final block list

- comskip.c
- mpeg2dec.c
Stores each frame's `pict_type` in the frame array. Also Shows whether a black frame is I/P/B-frame for debugging.
This might also be useful for further optimization later, for example we can limit logo detection to I-frame only.
> Record video frame picture type

- comskip.c
- platform.h
In #22 I switched from a semaphore to a mutex, which is incorrect since a mutex cannot be locked/unlocked from different threads.
This PR switches back to a semaphore in a cross-platform way that works on mac, linux and windows.
> Use semaphore instead of mutex for multithreaded synchronization

- .travis.yml
- README.md
This will build comskip on an Ubuntu Precise machine after every commit and try to run it against a simple sample video file. Should help ensure we don't break linux compatibility as has happened multiple times recently with the addition of threading support, etc.
> Add automated builds using TravisCI

- comskip.c
This patch adds a --threads command-line parameter. By passing an int as the parameter value, the user can control the number of threads comskip will use without editing their ini file.
> Add --threads parameter for controlling the number of threads used.

- mpeg2dec.c
When there is no \ in HomeDir and has an upper address in memory, subtraction in max() can give a positive huge number (two's complement).
I was loading comskip as DSO. DSO addresses are higher in memory layout.
Bug example (in x86_64):
> #include <stdio.h>
#define max(a,b) ((a) > (b)? (a) : (b))
int main() 
{
size_t len = (size_t)max(0, (char *)0 - (char *)0xff00000000000000);
printf("LEN=%ld\n", len);
return 0;
}
> bugfix: potential SIGSEGV

- comskip.c
Additional debug also added to ensure we don't go outside the area of
memory allocated; this is optional and switched off by default
> bug #65: invalid memory initialization of frame_ptr

- configure.ac
Fixes #50; when compiling Comskip on a Linux environment the version shown is not correct because it's inherited from the configure script instead of **comskip.h** (**PACKAGE_STRING** already defined).
> Sync configure.ac version with comskip.h

- mpeg2dec.c
Check if .ini is set to hw decoding and the RPi decoder is present. If yes, it is used instead of the ffmpeg default.
> Added hardware decoding for Raspberry Pi

- configure.ac
Adding AM_PROG_CC_C_O to configure.ac fixes error running autogen.sh on Centos 7.4
> Added AM_PROG_CC_C_O for missing legacy source

- configure.ac
Linux distributions hate automagic dependencies. :)
P.S. The version number in AC_INIT is outdated.
> Allow GUI to be explicitly enabled or disabled with configure

- configure.ac
Allows to display the correct program version when running 'autogen' by picking up the version string from comskip.h.
> Sync version in comskip.h with configure.ac

- comskip.c
- configure.ac
- mpeg2dec.c
The way comskip is using avcodec_find_decoder(...) meant that it was not always selecting the fastest avaiable decoder when multiple decoders for a given media file are available. If you have libavcodec compiled with support for cuvid/vdpau and a recent NVIDIA card, then using those codecs are faster.
This PR added specific support for choosing those codecs if they are avaialble. It also adds an option (--decoders) which will list all available decoders on your system.
> Allow selection of cuvid/vdpau codecs

- comskip.c
All CC data was off by two frames when loaded from the CSV.
I couldn't find any reason why this should have the `- 2` and without it the resulting log matches one from the `.mpg`.
> Fix loading CC data from CSV

- comskip.c
Fixes issues where processing a CSV was different than source material.
I've been trying to understand why processing a `.csv` has different results than the source material.
One issue I found was that a frame's `currentGoodEdge` was being evaluated against `logo_threshold`. In some cases the `currentGoodEdge` was `0.800301` in the original frame. When evaluated in `currentGoodEdge > logo_threshold` it would be true, but the CSV only had precision of 2 decimal places which meant that `currentGoodEdge` was only `0.8` and would not evaluate as true.
To prevent these sorts of issues I added a few more decimal places to these columns.
> Change precision in CSV

- video_out_sdl.c
Error reported (see also #121 ) :
```
/usr/bin/ld: comskip_gui-video_out_sdl.o:./video_out_sdl.c:309: multiple definition of `result'; ccextratorwin/comskip_gui-general_loop.o:./ccextratorwin/general_loop.c:20: first defined here
```
So, moving result variable ( video_out_sdl.c ) inside the only function that uses it.
> Fix gcc10 compilation

- appveyor.yml
The appveyor.yml CI build script is broken, because the ffmpeg 3.3.1 files it attempts to download are from a website that no longer exists: https://ffmpeg.zeranoe.com
The ffmpeg 3.3.1 files for Windows x64 were downloaded from the internet archive and pushed to a ffmpeg-release repo on my account.
The script now points to the newly created repo.
> GHI 135: Corrected build error emitted by AppVeyor

- comskip.c
Corrected how command line parameters are printed to console to avoid access violation crash that can occur on Windows when the length of a given parameter is greater than MAX_ARG, which is limited to 260 char.
Example string used for testing:
```
C:\Users\AhiyaHiya\Applications\Utility\Media\ComSkip\ComSkip.exe "--ini=C:\Users\AhiyaHiya\Applications\Utility\Media\ComSkip\comskip.ini" --output=C:\Users\AhiyaHiya\Media\Television\2020\08\20\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING -t --verbose=1 "C:\Users\AhiyaHiya\Media\Television\2020\08\20\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING\SOMEREALLLYLONGSTRING\ABC Good Morning America (2021) - 2020-08-20 07 00 00 - ABC Good Morning America.ts"
```
> Corrected LoadSettings command line argument print out

- appveyor.yml
- configure.ac
- mpeg2dec.c
Uses swscale to convert to 8-bit, because `SubmitFrame` uses `frame_ptr = pFrame->data[0];` and assumes `unsigned char *frame_ptr` meaning 8-bit per pixel.
> Add support for 10-bit video

- Dockerfile
git:// protocol is no longer supported, replaced with https://
```
#6 17.09 Cloning into 'Comskip'...
#6 17.37 fatal: remote error:
#6 17.37   The unauthenticated git protocol on port 9418 is no longer supported.
#6 17.37 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
> Update Comskip repository link

- configure.ac
- mpeg2dec.c
Partly derived from #150; fixes #142. Seems to work in my experimenting, but I don't have a broad test suite for this; in particular, this likely breaks some of the AC3-specific code (I have no idea what that code is supposed to do, whether or not it's still relevant with modern ffmpeg, or how to test it).
This works with both lavf/lavc≤58 and lavf/lavc≥59, but requires at least lavf 57.33.100 / lavc 57.37.100 (versions from 2016).
> Update to modern ffmpeg codec APIs

- comskip.c
- mpeg2dec.c
Add support for Intel Quick Sync Video acceleration.
Tested on an Intel i5-12400T with [jellyfin-ffmpeg](https://github.com/jellyfin/jellyfin-ffmpeg)
> Add Intel Quick Sync Video acceleration (QSV) support

- comskip.c
According to the documentation, setting delay_logo_search=1 delays it for added_recording amount of minutes. This did not work as expected.
> Fix delay_logo_search when using added_recording
