erikkaashoek/Comskip

comskip.c

Addresses https://github.com/erikkaashoek/Comskip/commit/9965b0165c8d142556f0be284e0e13ee5be63190#commitcomment-12533738

Use `get_frame_pts` instead of `frame/fps`

---

comskip.c
mpeg2dec.c

Fix some compiler warnings

---

Makefile.am

Adds gcc automatic automatic optimization for the hardware gcc is running on.

Enable gcc native optimization detection

---

Makefile.am
appveyor.yml

Appveyor support

---

appveyor.yml
mpeg2dec.c

WIP, do not merge until tests pass

support ffmpeg 3.0

---

comskip.c

Added output to use with mkvmerger or mkvpropedit to add chapters to mkv
files.

Add mkvtoolnix output

---

README.md

Build instructions for 16.04 Ubuntu

---

.gitignore
appveyor.yml
mpeg2dec.c

Address PTS/DTS issues with cuvid (cuvid does not set DTS)

cuvid updates

---

comskip.c
video_out_sdl.c

This speeds up moving 'just a little bit' when doing commercial review.

Added support for moving forward or backward by 1/2 second at a time.

---

.travis.yml
mpeg2dec.c

Do not close debugwindow at the end of the scan on Linux

---

comskip.c

Match all of the other supporting files that are created as part of the run.

Put .tun file in the workbasename location

---

comskip.c

I found a few places that caused the CSV-based importing to produce different results from the source file importing.

Fix cases where variables are initialized differently

---

configure.ac
video_out_sdl.c

this makes `votest` and `comskip-gui` work on macOS again

Upgrade to SDL2

---

README.md

Compile Comskip win32 using Ubuntu cross compiler MinGW-w64

Instructions for cross compiling Comskip on Ubuntu

---

appveyor.yml

cc https://github.com/erikkaashoek/Comskip/pull/143#issuecomment-1050380357

Build in CI with ffmpeg 4.4.1

---

comskip.c

I've added this but I have no way of testing it as I can't actually compile the project

Add logo at side check

---

mpeg2dec.c

Use `AVStream->codecpar` instead of `->codec`. This is required for ffmpeg 5.0
cc #142

Get ready for ffmpeg 5.0 deprecations

---

appveyor.yml
mpeg2dec.c

fixes https://github.com/erikkaashoek/Comskip/pull/152#issuecomment-1230881968

Fix segv in audio code and other asan errors

---

comskip.c
mpeg2dec.c

commits taken from @bsperduto fork

fixes building of comskip with ffmpeg 6

---

mpeg2dec.c

CUDA codec for vc1 is `vc1_cuvid`

Fix VC1 CUDA decoding

---

.github/workflows/build.yaml
.gitignore
comskip.c
mpeg2dec.c
platform.h
video_out_dx.c

I wanted to build Comskip with ffmpeg7, as there were a bunch off errors the following commits fix those and keep compatibility with ffmpeg5/6.

Build comskip with ffmpeg7

---

.github/workflows/build.yaml
README.md

Canonical names of some brew packages has changed, so updating those.

Update brew packages to canonical names

---

comskip.c

Fix build with gcc-15 and -std=c23
